name: lottie
description: Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
version: 1.0.1
homepage: https://github.com/xvrh/lottie-flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  archive:
  characters: 
  charcode: 
  collection:
  flutter:
    sdk: flutter
  logging: 
  meta:  
  path:  
  vector_math:  

dev_dependencies:
  analyzer:  
  build_runner:
  dart_style:
  flutter_test:
    sdk: flutter
  mockito:
  pub_semver:
  yaml:  
